### PR TITLE
[BREAKING] Read/write effect labels

### PR DESCRIPTION
**Pull request by zudov**
Just a little idea. Might be an overkill, but why would finer-grained effects hurt. What do you think?

### CODE REVIEW

**Comment by zudov** [comment]
One issue here is that `read`, `write` names might also be used by other libraries, so if we want to have it they better be `readRef`, `writeRef`

**Comment by texastoland** [comment]
Looks like this got overlooked! Presumably you could make some guarantees about purity if it only reads? Does `ST` not kinda do that?

**Comment by paf31** [comment]
Yes, sorry this was overlooked. Is there a compelling case for separating these out? I don't think either one on its own is a guarantee of any kind of purity unfortunately.

**Comment by zudov** [comment]
Looking at it now, I don't think it's very important, and I don't have a good use case. Additionally, it's way too breaking for doing it with no good reason.

**Pull request closed without merging**
